# Makefile - makefile for C++ factory example RTP
#
# modification history
# --------------------
# 01c,18jun09,mze  adding RTP obj rules
# 01b,01oct04,job Added DOC_FILES rule
# 01a,13jul04,sn  written
#
# DESCRIPTION
# This file contains the makefile rules for building the C++ factory RTP

EXE = factory.vxe

RTP_BASE_DIR = factory

OBJS =  factory.o 

DOC_FILES = factory.cpp

include $(WIND_USR)/make/rules.rtp
