# Makefile - makefile for dining philosophers example RTP
#
# modification history
# --------------------
# 01c,22jun09,mze  adding RTP obj rules
# 01b,12nov03,job  Changed TGT_DIR to WIND_USR and extension to .vxe
# 01a,29sep03,md   written
#
# DESCRIPTION
# This file contains the makefile rules for building the dining philosophers
# RTP module.  
#
# Set the following environment variables prior to building:

EXE = phil.vxe

RTP_BASE_DIR = philosophers

OBJS =  phil.o 

include $(WIND_USR)/make/rules.rtp
