# Makefile - makefile for ED&R demo RTP
#
# modification history
# --------------------
# 01d,18jun09,mze  adding RTP object rules
# 01c,01oct04,job  Renamed to .c and added DOC_FILES rule
# 01b,12jan04,pad  Changed obsolete suffix .rtp with correct one: .vxe
# 01a,31oct03,dbs  written
#
# DESCRIPTION
# This file contains the makefile rules for building the edrdemo RTP

TGT_DIR=$(WIND_BASE)/target/usr

EXE = edrdemo.vxe

RTP_BASE_DIR = edrdemo

OBJS =  edrDemo.o 

DOC_FILES = edrDemo.c

include $(TGT_DIR)/make/rules.rtp
